### ISSUE TITLE
⚠️ Release 4.28.0 introduced a breaking change because a previous optional parameter is now required for `changeFieldControl`

### ISSUE THREAD

**Issue by Swissbite** [contentful/contentful-migration#1466]
Release 4.28.0 introduced a breaking change because a previous optional parameter is now required for `changeFieldControl`.

Previously something like this was ok: 
```TypeScript 
transitionRedirect.changeFieldControl("sourcePath", "builtin", "singleLine"); 
``` 
With v4.28.0 this causes a TypeScript compile error: `Error TS2345: Argument of type '"builtin"' is not assignable to parameter of type '"extension" | "app"`.

Reason: https://github.com/contentful/contentful-migration/compare/v4.27.0...v4.28.0#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8R309 

A workaround is currently 
```TypeScript
transitionRedirect.changeFieldControl("sourcePath", "builtin", "singleLine", {}); //empty config object 
```

**Comment by chrishelgert** [comment]
Introduced with #1462
