### ISSUE TITLE
Typescript errors when updating to 4.9.5 

### ISSUE THREAD

**Issue by Spritefarmer** [contentful/contentful-migration#1115]
## Actual Behavior

Typescript errors after updating module to v 4.9.5

error TS2305: Module '"contentful-migration"' has no exported member 'runMigration'.
error TS2305: Module '"contentful-migration"' has no exported member 'RunMigrationConfig'.

## Possible Solution

going back to 4.9.4 resolved the issue.

## Steps to Reproduce

npm install 

## Environment

-   **Node Version**: v14.19.3
-   **Package Manager Version**: 6.14.17
-   **Operating System**: MacOS 12.4
-   **Package Version**: 4.9.5

**Comment by mareksuscak** [comment]
Yeah, same issue on my end. Looks like the types were not exported correctly in this build. Here's what I see:

<img width="469" alt="CleanShot 2022-09-26 at 23 59 38@2x" src="https://user-images.githubusercontent.com/613647/192388354-4414ff9a-7ade-43b3-8942-b89b0df021f6.png">

**Comment by marcolink** [comment]
Closing due to inactivity
